#!/usr/bin/env python3
"""Simplified launch server for testing without vLLM dependencies."""

import argparse
import asyncio
import json
import logging
from typing import AsyncGenerator, Dict, List, Optional

import uvicorn
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

logger = logging.getLogger(__name__)

app = FastAPI(title="FastMoE Inference Server")


class GenerateRequest(BaseModel):
    prompt: str
    max_tokens: int = 100
    temperature: float = 0.7
    top_p: float = 0.9


class GenerateResponse(BaseModel):
    text: str
    usage: Dict[str, int]


class ModelServer:
    """Model server for FastMoE inference (stub implementation)."""
    
    def __init__(
        self,
        model_path: str,
        tp_size: int = 1,
        cpu_mem_bdw: int = 76,
        avg_prompt_len: int = 77,
        gen_len: int = 32,
    ):
        self.model_path = model_path
        self.tp_size = tp_size
        self.cpu_mem_bdw = cpu_mem_bdw
        self.avg_prompt_len = avg_prompt_len
        self.gen_len = gen_len
        
        logger.info(f"Initializing model server with:")
        logger.info(f"  Model path: {model_path}")
        logger.info(f"  TP size: {tp_size}")
        logger.info(f"  CPU memory bandwidth: {cpu_mem_bdw}")
        logger.info(f"  Average prompt length: {avg_prompt_len}")
        logger.info(f"  Generation length: {gen_len}")
        
        # In a real implementation, this would load the actual model
        self.model = self._load_model()
    
    def _load_model(self):
        """Load the model. For now, this is a stub."""
        logger.info(f"Loading model from {self.model_path}")
        logger.info("Model loaded successfully (stub implementation)")
        return None
    
    async def generate(self, request: GenerateRequest) -> GenerateResponse:
        """Generate text from the model."""
        # This is a stub implementation that simulates realistic token counts
        prompt_tokens = max(10, len(request.prompt.split()))
        completion_tokens = min(request.max_tokens, self.gen_len)
        
        # Simulate some processing time
        await asyncio.sleep(0.1)
        
        generated_text = f"[Generated by {self.model_path} with TP={self.tp_size}] Response to: {request.prompt[:50]}..."
        if len(request.prompt) > 50:
            generated_text += "... (truncated)"
        
        return GenerateResponse(
            text=generated_text,
            usage={
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": prompt_tokens + completion_tokens
            }
        )


# Global model server instance
model_server: Optional[ModelServer] = None


@app.on_event("startup")
async def startup_event():
    """Initialize the model server on startup."""
    logger.info("FastMoE inference server started successfully!")


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy", "model": model_server.model_path if model_server else "none"}


@app.post("/generate", response_model=GenerateResponse)
async def generate_text(request: GenerateRequest):
    """Generate text endpoint."""
    if model_server is None:
        raise HTTPException(status_code=503, detail="Model server not initialized")
    
    try:
        response = await model_server.generate(request)
        return response
    except Exception as e:
        logger.error(f"Error generating text: {e}")
        raise HTTPException(status_code=500, detail=str(e))


def main():
    """Main entry point for the server."""
    parser = argparse.ArgumentParser(description="FastMoE Inference Server")
    parser.add_argument("--model-path", required=True, help="Path to the model")
    parser.add_argument("--port", type=int, default=8000, help="Port to run the server on")
    parser.add_argument("--host", default="0.0.0.0", help="Host to bind the server to")
    parser.add_argument("--tp-size", type=int, default=1, help="Tensor parallel size")
    parser.add_argument("--cpu-mem-bdw", type=int, default=76, help="CPU memory bandwidth")
    parser.add_argument("--avg-prompt-len", type=int, default=77, help="Average prompt length")
    parser.add_argument("--gen-len", type=int, default=32, help="Generation length")
    parser.add_argument("--log-level", default="INFO", help="Log level")
    
    args = parser.parse_args()
    
    # Set up logging
    logging.basicConfig(
        level=getattr(logging, args.log_level.upper()),
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    )
    
    # Initialize the global model server
    global model_server
    model_server = ModelServer(
        model_path=args.model_path,
        tp_size=args.tp_size,
        cpu_mem_bdw=args.cpu_mem_bdw,
        avg_prompt_len=args.avg_prompt_len,
        gen_len=args.gen_len,
    )
    
    # Run the server
    logger.info(f"Starting server on {args.host}:{args.port}")
    uvicorn.run(
        app,
        host=args.host,
        port=args.port,
        log_level=args.log_level.lower()
    )


if __name__ == "__main__":
    main()